### ISSUE TITLE
Diaeresis plus smooth breathing

### ISSUE THREAD

**Issue by sk00gle** [hmteditors/gustavus#5]
I'm in need of a way to type a smooth breathing with a diaeresis over the same vowel. The team and I have done some extensive looking around, and we've had little to no success.

**Comment by StephanieML** [comment]
what vowel do you need?

**Comment by edugdale** [comment]
Hi Stephanie,

We're trying to do our first XML editing at the moment and trying to access the virtual machine. We're following the instructions at http://www.homermultitext.org/summer2014/tips/GitandVirtualMachinesHO.html

In Terminal, we get as far as the 5th line (see below), but when we enter sh refresh-hmt.sh we get the responses "Can't open refresh-hmt.sh"
Do you know what we might be doing wrong here?

Thanks, Eric

cd PathwayToYourRepository/hmt-vm (will get you to your virtual machine)
vagrant up (starts up the virtual machine)
vagrant ssh (connects to the virtual machine via a secure shell)
cd /vagrant (puts you in the shared directory on the virtual machine)
sh refresh-hmt.sh (checks for updates to the virtual machine)

**Comment by StephanieML** [comment]
Hi Eric, these are instructions for the old VM. Reference these links from now on: http://homermultitext.github.io/hmt-docs/vm/
