### ISSUE TITLE
Combine Iliad Editions

### ISSUE THREAD

**Issue by StephanieML** [hmteditors/gustavus#6]
Hey guys, I just noticed that you've been making new files for every folio of lines you do a text edition of. You can paste those all into the one VenetusA-Iliad file. I suggest this just because naming them 1,2,3,4 makes it sound like you're editing Books 1, 2, 3, and 4. I don't want our file systems to get confused so if you can move everything over to the one file, I can delete the spares for you!

**Comment by amiegoblirsch** [comment]
Alright good to know, we'll combine them and then delete the others!

Thanks,

Amie


Quoting StephanieML <notifications@github.com>:

> Hey guys, I just noticed that you've been making new files for every  
> folio of lines you do a text edition of. You can paste those all  
> into the one VenetusA-Iliad file. I suggest this just because naming  
> them 1,2,3,4 makes it sound like you're editing Books 1, 2, 3, and  
> 4. I don't want our file systems to get confused so if you can move  
> everything over to the one file, I can delete the spares for you!
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/hmteditors/gustavus/issues/6


-- 
Amie Goblirsch
Classics Major '16
President, Eta Sigma Phi
Gustavus Adolphus College
agoblirs@gustavus.edu
