### ISSUE TITLE
Possible new abbreviation

### ISSUE THREAD

**Issue by sk00gle** [hmteditors/gustavus#7]
While working on the third intermarginal scholion for folio 176 verso, we stumbled across what might be a new abbreviation. Erbse gives us βραχὺ. Is he correct? And is this a standard abbreviation that we just haven't seen, or will we need to use the abbr/exp pair?
![possible new abbreviation](https://cloud.githubusercontent.com/assets/7852092/7357556/35d5dcae-ecf5-11e4-82f9-ebb538bc8e52.PNG)

**Comment by StephanieML** [comment]
this a common abbreviation but you should mark it up with 'abbr' 'expan' because it's not consistently the same ending.
