### ISSUE TITLE
Is this a bona fide tau?

### ISSUE THREAD

**Issue by edugdale** [hmteditors/gustavus#9]
Hi Stephanie,

On folio 177 recto ad 13.675, the second tau in the ὅττί looks very strange: is this a ligature you have come across before?
urn:cite:hmt:vaimg.VA177RN-0348@0.181,0.4621,0.092,0.0255

Thanks,
Eric

**Comment by StephanieML** [comment]
yes, super weird, but definitely the double tau ligature. I think he does this to avoid making it look like a pi
